name: 'Terraform CI/CD'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }} # Make sure to set this secret in your repository

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}' # Make sure to set this secret in your repository

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest # Or specify a version e.g., 1.0.0

      - name: 'Terraform Init'
        id: init
        run: terraform init
        working-directory: ./terraform # Assuming your Terraform files are in a 'terraform' subdirectory

      - name: 'Terraform Validate'
        id: validate
        run: terraform validate -no-color
        working-directory: ./terraform

      - name: 'Terraform Plan'
        id: plan
        run: terraform plan -no-color -input=false -out=tfplan
        working-directory: ./terraform
        # Only run on pull requests or direct pushes to main (not on merges)
        if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')

      - name: 'Terraform Apply'
        id: apply
        run: terraform apply -auto-approve -input=false tfplan
        working-directory: ./terraform
        # Only run on pushes to the main branch (e.g., after a PR is merged)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
